-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('promotion-assets', 'promotion-assets', true);

CREATE POLICY "允许匿名用户查看推广资源" ON storage.objects
FOR SELECT USING (bucket_id = 'promotion-assets');

CREATE POLICY "允许认证用户上传推广资源" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'promotion-assets' AND
  auth.role() = 'authenticated'
);