-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID NOT NULL REFERENCES public.demands(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  period VARCHAR(50) NOT NULL,
  remark TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  viewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看审核通过需求的报价" ON public.quotes
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.demands d 
    WHERE d.id = demand_id 
    AND d.status IN ('approved', 'connected', 'completed')
  )
);

CREATE POLICY "需求发布者可查看自己需求的报价" ON public.quotes
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.demands d 
    WHERE d.id = demand_id 
    AND d.user_id = auth.uid()
  )
);

CREATE POLICY "开发者可查看自己的报价" ON public.quotes
FOR SELECT USING (developer_id = auth.uid());

CREATE POLICY "开发者可提交报价" ON public.quotes
FOR INSERT WITH CHECK (
  auth.uid() IS NOT NULL 
  AND developer_id = auth.uid()
);

CREATE POLICY "开发者可更新自己的报价" ON public.quotes
FOR UPDATE USING (developer_id = auth.uid());

COMMENT ON TABLE public.quotes IS '需求撮合-报价表';
COMMENT ON COLUMN public.quotes.status IS '状态：pending待查看/viewed已查看/connected已对接/rejected已拒绝/expired已失效';