-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 启用 storage.objects 表的 RLS
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 删除可能存在的旧策略
DROP POLICY IF EXISTS "允许所有用户上传推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许所有用户查看推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许所有用户更新推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许所有用户删除推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许匿名用户上传推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许匿名用户查看推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许匿名用户更新推广资源" ON storage.objects;
DROP POLICY IF EXISTS "允许匿名用户删除推广资源" ON storage.objects;

-- 创建新的策略 - 允许所有用户（包括匿名）操作 promotion-assets bucket
CREATE POLICY "promotion_assets_insert" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'promotion-assets');

CREATE POLICY "promotion_assets_select" ON storage.objects
FOR SELECT USING (bucket_id = 'promotion-assets');

CREATE POLICY "promotion_assets_update" ON storage.objects
FOR UPDATE USING (bucket_id = 'promotion-assets');

CREATE POLICY "promotion_assets_delete" ON storage.objects
FOR DELETE USING (bucket_id = 'promotion-assets');