-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================


-- 推广链接表
CREATE TABLE promotion_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  promoter_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  tool_id UUID REFERENCES tools(id) ON DELETE CASCADE,
  code TEXT UNIQUE NOT NULL,
  click_count INTEGER DEFAULT 0,
  conversion_count INTEGER DEFAULT 0,
  commission_earned DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 推广点击记录表
CREATE TABLE promotion_clicks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  link_id UUID REFERENCES promotion_links(id) ON DELETE CASCADE,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 佣金提现记录表
CREATE TABLE commission_withdrawals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  promoter_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_method TEXT,
  payment_account TEXT,
  processed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 浏览历史表
CREATE TABLE browsing_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  tool_id UUID REFERENCES tools(id) ON DELETE CASCADE,
  viewed_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, tool_id)
);

-- 启用RLS
ALTER TABLE promotion_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotion_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE commission_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE browsing_history ENABLE ROW LEVEL SECURITY;

-- 推广链接策略
CREATE POLICY "推广者可查看自己的推广链接" ON promotion_links
  FOR SELECT USING (promoter_id = auth.uid());

CREATE POLICY "推广者可创建推广链接" ON promotion_links
  FOR INSERT WITH CHECK (promoter_id = auth.uid());

CREATE POLICY "管理员可查看所有推广链接" ON promotion_links
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 点击记录策略
CREATE POLICY "推广者可查看自己链接的点击" ON promotion_clicks
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM promotion_links 
      WHERE id = link_id AND promoter_id = auth.uid()
    )
  );

CREATE POLICY "任何人可记录点击" ON promotion_clicks
  FOR INSERT WITH CHECK (true);

-- 提现记录策略
CREATE POLICY "推广者可查看自己的提现记录" ON commission_withdrawals
  FOR SELECT USING (promoter_id = auth.uid());

CREATE POLICY "推广者可申请提现" ON commission_withdrawals
  FOR INSERT WITH CHECK (promoter_id = auth.uid());

-- 浏览历史策略
CREATE POLICY "用户可查看自己的浏览历史" ON browsing_history
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "用户可添加浏览历史" ON browsing_history
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "用户可删除自己的浏览历史" ON browsing_history
  FOR DELETE USING (user_id = auth.uid());
