-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为所有表添加管理员完整权限策略

-- 1. tools 表 - 管理员可修改所有工具
CREATE POLICY "管理员可修改所有工具" ON tools FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 2. demands 表 - 管理员可查看和管理所有需求
CREATE POLICY "管理员可查看所有需求" ON demands FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

CREATE POLICY "管理员可修改所有需求" ON demands FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 3. quotes 表 - 管理员可查看和管理所有报价
CREATE POLICY "管理员可查看所有报价" ON quotes FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 4. chat_conversations 表 - 管理员可查看所有会话
CREATE POLICY "管理员可查看所有聊天会话" ON chat_conversations FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 5. chat_messages 表 - 管理员可查看所有消息
CREATE POLICY "管理员可查看所有聊天消息" ON chat_messages FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 6. browsing_history 表 - 管理员可查看所有浏览记录
CREATE POLICY "管理员可查看所有浏览历史" ON browsing_history FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 7. favorites 表 - 管理员可查看所有收藏
CREATE POLICY "管理员可查看所有收藏" ON favorites FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 8. comments 表 - 管理员可管理所有评论
CREATE POLICY "管理员可管理所有评论" ON comments FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 9. promotion_contents 表 - 管理员可查看所有推广内容
CREATE POLICY "管理员可查看所有推广内容" ON promotion_contents FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 10. promotion_links 表 - 管理员可管理所有推广链接
CREATE POLICY "管理员可管理所有推广链接" ON promotion_links FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 11. promotion_tasks 表 - 管理员可查看所有悬赏任务
CREATE POLICY "管理员可查看所有悬赏任务" ON promotion_tasks FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 12. promotion_settlements 表 - 管理员可管理所有结算
CREATE POLICY "管理员可管理所有结算" ON promotion_settlements FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 13. user_operation_logs 表 - 管理员可查看所有操作日志
CREATE POLICY "管理员可查看所有操作日志" ON user_operation_logs FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 14. connections 表 - 管理员可查看所有对接记录
CREATE POLICY "管理员可查看所有对接记录" ON connections FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- 15. reviews 表 - 管理员可管理所有评价
CREATE POLICY "管理员可管理所有评价" ON reviews FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);