-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为用户表添加手机号字段
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone TEXT UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT false;

-- 创建验证码表（用于存储临时验证码）
CREATE TABLE IF NOT EXISTS phone_verifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone TEXT NOT NULL,
  code TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  used BOOLEAN DEFAULT false
);

-- 启用RLS
ALTER TABLE phone_verifications ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户创建验证码
CREATE POLICY "允许创建验证码" ON phone_verifications FOR INSERT TO anon WITH CHECK (true);

-- 允许匿名用户查询自己的验证码
CREATE POLICY "允许查询验证码" ON phone_verifications FOR SELECT TO anon USING (true);