-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.demands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  type VARCHAR(50) NOT NULL,
  category VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  budget_min INTEGER,
  budget_max INTEGER,
  budget_type VARCHAR(20) NOT NULL DEFAULT 'fixed',
  period VARCHAR(50) NOT NULL,
  contact_info VARCHAR(200),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  view_count INTEGER DEFAULT 0,
  quote_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.demands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看审核通过的需求" ON public.demands
FOR SELECT USING (status IN ('approved', 'connected', 'completed'));

CREATE POLICY "需求发布者可查看自己的需求" ON public.demands
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "已登录用户可发布需求" ON public.demands
FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "需求发布者可更新自己的需求" ON public.demands
FOR UPDATE USING (user_id = auth.uid());

COMMENT ON TABLE public.demands IS '需求撮合-需求表';
COMMENT ON COLUMN public.demands.status IS '状态：pending待审核/approved审核通过/connected对接中/completed已完成/closed已关闭/rejected已驳回';