-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户平台授权表
CREATE TABLE IF NOT EXISTS user_platform_auth (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- 平台信息
  platform VARCHAR(50) NOT NULL, -- github, jike, juejin, weibo, zhihu
  platform_user_id VARCHAR(200),
  platform_username VARCHAR(200),
  
  -- 授权信息
  access_token TEXT,
  refresh_token TEXT,
  token_expires_at TIMESTAMP,
  
  -- 额外配置（JSON格式存储各平台特有配置）
  config JSONB DEFAULT '{}',
  
  -- 状态
  is_active BOOLEAN DEFAULT true,
  last_used_at TIMESTAMP,
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  
  UNIQUE(user_id, platform)
);

-- 启用RLS
ALTER TABLE user_platform_auth ENABLE ROW LEVEL SECURITY;

-- RLS策略
CREATE POLICY "用户查看自己的平台授权" ON user_platform_auth
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建平台授权" ON user_platform_auth
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户更新自己的平台授权" ON user_platform_auth
FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户删除自己的平台授权" ON user_platform_auth
FOR DELETE USING (auth.uid() = user_id);