-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- Function to record landing page view (first jump - not billed)
CREATE OR REPLACE FUNCTION record_promotion_landing_view(
  promotion_code TEXT,
  tool_id UUID,
  ip_address TEXT,
  user_agent TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  link_record RECORD;
BEGIN
  -- Get promotion link
  SELECT * FROM promotion_links WHERE code = promotion_code LIMIT 1 INTO link_record;
  
  IF link_record IS NULL THEN
    RETURN;
  END IF;
  
  -- Update promotion link landing page views
  UPDATE promotion_links
  SET landing_page_views = COALESCE(landing_page_views, 0) + 1
  WHERE id = link_record.id;
  
  -- Record landing page click
  INSERT INTO promotion_landing_clicks (
    link_id,
    promoter_id,
    tool_id,
    ip_address,
    user_agent,
    referrer
  ) VALUES (
    link_record.id,
    link_record.promoter_id,
    tool_id,
    ip_address,
    user_agent,
    NULL
  );
END;
$$;

-- Function to record conversion (second jump - billed)
CREATE OR REPLACE FUNCTION record_promotion_conversion(
  promotion_code TEXT,
  tool_id UUID,
  promoter_id UUID,
  ip_address TEXT,
  user_agent TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  link_record RECORD;
  settings_record RECORD;
  conversion_amount NUMERIC := 0;
  platform_fee NUMERIC := 0;
  promoter_earning NUMERIC := 0;
  developer_cost NUMERIC := 0;
BEGIN
  -- Get promotion link
  SELECT * FROM promotion_links 
  WHERE code = promotion_code AND promoter_id = promoter_id 
  LIMIT 1 INTO link_record;
  
  IF link_record IS NULL THEN
    RETURN;
  END IF;
  
  -- Get tool promotion settings
  SELECT * FROM tool_promotion_settings 
  WHERE tool_id = tool_id AND is_active = true 
  LIMIT 1 INTO settings_record;
  
  -- Calculate fees if settings exist
  IF settings_record IS NOT NULL THEN
    conversion_amount := COALESCE(settings_record.pay_per_conversion, 0);
    platform_fee := conversion_amount * COALESCE(settings_record.platform_fee_percentage, 10) / 100;
    promoter_earning := conversion_amount - platform_fee;
    developer_cost := conversion_amount;
  END IF;
  
  -- Update promotion link conversion count
  UPDATE promotion_links
  SET 
    conversion_count = COALESCE(conversion_count, 0) + 1,
    valid_conversions = COALESCE(valid_conversions, 0) + 1,
    commission_earned = COALESCE(commission_earned, 0) + promoter_earning
  WHERE id = link_record.id;
  
  -- Update promoter total earnings
  UPDATE promoters
  SET total_earned = COALESCE(total_earned, 0) + promoter_earning
  WHERE user_id = promoter_id;
  
  -- Record settlement if amount > 0
  IF conversion_amount > 0 THEN
    INSERT INTO promotion_settlements (
      link_id,
      promoter_id,
      tool_id,
      developer_id,
      settlement_type,
      amount,
      platform_fee,
      promoter_earning,
      developer_cost,
      status
    ) VALUES (
      link_record.id,
      promoter_id,
      tool_id,
      (SELECT developer_id FROM tools WHERE id = tool_id),
      'conversion',
      conversion_amount,
      platform_fee,
      promoter_earning,
      developer_cost,
      'pending'
    );
  END IF;
END;
$$;