-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS platform VARCHAR(50);
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS platform_username VARCHAR(100);
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS follower_count INTEGER DEFAULT 0;
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS content_category VARCHAR(50);
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS contact_info VARCHAR(200);
ALTER TABLE public.promoters ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT true;

COMMENT ON COLUMN public.promoters.platform IS '主要推广平台，如微博、抖音、B站、小红书等';
COMMENT ON COLUMN public.promoters.platform_username IS '平台账号名称';
COMMENT ON COLUMN public.promoters.follower_count IS '粉丝数量';
COMMENT ON COLUMN public.promoters.content_category IS '内容类型，如科技、生活、教育、游戏等';
COMMENT ON COLUMN public.promoters.bio IS '个人简介';
COMMENT ON COLUMN public.promoters.contact_info IS '联系方式';
COMMENT ON COLUMN public.promoters.is_public IS '是否公开资料供开发者查看';