-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE promotion_publish_logs ADD COLUMN IF NOT EXISTS error_type VARCHAR(50);
ALTER TABLE promotion_publish_logs ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS user_operation_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action VARCHAR(100) NOT NULL,
  resource_type VARCHAR(50),
  resource_id UUID,
  details JSONB,
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE user_operation_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "用户可查看自己的操作日志" ON user_operation_logs
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "系统可插入操作日志" ON user_operation_logs
  FOR INSERT WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_operation_logs_user_id ON user_operation_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_operation_logs_created_at ON user_operation_logs(created_at);