-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE tool_platform_links ADD COLUMN IF NOT EXISTS qr_code_url TEXT;

COMMENT ON COLUMN tool_platform_links.qr_code_url IS '平台二维码图片URL，用于无法直接跳转的平台（如小程序）';