-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建增加需求浏览量的函数
CREATE OR REPLACE FUNCTION increment_demand_view(demand_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE demands
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE id = demand_id;
END;
$$;

-- 创建增加需求报价数的函数
CREATE OR REPLACE FUNCTION increment_demand_quote_count(demand_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE demands
  SET quote_count = COALESCE(quote_count, 0) + 1
  WHERE id = demand_id;
END;
$$;

-- 添加 quote_count 字段到 demands 表（如果不存在）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'demands' AND column_name = 'quote_count'
  ) THEN
    ALTER TABLE demands ADD COLUMN quote_count INTEGER DEFAULT 0;
  END IF;
END $$;