-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除旧的RLS策略
DROP POLICY IF EXISTS "允许创建验证码" ON phone_verifications;
DROP POLICY IF EXISTS "允许查询验证码" ON phone_verifications;

-- 创建新的RLS策略，允许所有用户操作
CREATE POLICY "允许所有用户创建验证码" ON phone_verifications FOR INSERT WITH CHECK (true);
CREATE POLICY "允许所有用户查询验证码" ON phone_verifications FOR SELECT USING (true);
CREATE POLICY "允许所有用户更新验证码" ON phone_verifications FOR UPDATE USING (true);

-- 确保profiles表有正确的RLS策略
DROP POLICY IF EXISTS "允许匿名用户创建profiles" ON profiles;
CREATE POLICY "允许匿名用户创建profiles" ON profiles FOR INSERT WITH CHECK (true);