-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修改推广链接表，支持两步跳转追踪
ALTER TABLE promotion_links ADD COLUMN IF NOT EXISTS landing_page_views INTEGER DEFAULT 0;
ALTER TABLE promotion_links ADD COLUMN IF NOT EXISTS valid_conversions INTEGER DEFAULT 0;

-- 创建推广点击追踪表（记录进入详情页的点击）
CREATE TABLE IF NOT EXISTS promotion_landing_clicks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  link_id UUID NOT NULL REFERENCES promotion_links(id) ON DELETE CASCADE,
  promoter_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  ip_address TEXT,
  user_agent TEXT,
  referrer TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE promotion_landing_clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可记录推广点击" ON promotion_landing_clicks
  FOR INSERT WITH CHECK (true);

CREATE POLICY "推广者可查看自己的点击数据" ON promotion_landing_clicks
  FOR SELECT USING (promoter_id = auth.uid());

-- 修改工具推广设置表，更新付费逻辑字段
ALTER TABLE tool_promotion_settings 
  ADD COLUMN IF NOT EXISTS pay_per_landing_view DECIMAL(10,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pay_per_conversion DECIMAL(10,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_budget DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_budget DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS spent_amount DECIMAL(10,2) DEFAULT 0;

-- 创建推广费用结算记录表
CREATE TABLE IF NOT EXISTS promotion_settlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  link_id UUID NOT NULL REFERENCES promotion_links(id) ON DELETE CASCADE,
  promoter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  settlement_type VARCHAR(20) NOT NULL CHECK (settlement_type IN ('landing_view', 'conversion')),
  amount DECIMAL(10,4) NOT NULL,
  platform_fee DECIMAL(10,4) NOT NULL,
  promoter_earning DECIMAL(10,4) NOT NULL,
  developer_cost DECIMAL(10,4) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled')),
  created_at TIMESTAMP DEFAULT NOW(),
  paid_at TIMESTAMP
);

ALTER TABLE promotion_settlements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "开发者可查看自己的结算记录" ON promotion_settlements
  FOR SELECT USING (developer_id = auth.uid());

CREATE POLICY "推广者可查看自己的结算记录" ON promotion_settlements
  FOR SELECT USING (promoter_id = auth.uid());

CREATE POLICY "系统可创建结算记录" ON promotion_settlements
  FOR INSERT WITH CHECK (true);