-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 推广内容表
CREATE TABLE IF NOT EXISTS promotion_contents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- 基础信息
  title VARCHAR(200) NOT NULL,
  source_type VARCHAR(20) CHECK (source_type IN ('manual', 'ai_generate', 'import')) DEFAULT 'manual',
  source_id UUID,
  
  -- 内容数据（各平台版本）
  content JSONB NOT NULL DEFAULT '{}',
  
  -- 素材
  images TEXT[],
  videos TEXT[],
  
  -- 标签
  tags TEXT[],
  category VARCHAR(50),
  
  -- 状态
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'reviewing', 'approved', 'rejected', 'scheduled', 'publishing', 'published', 'archived')),
  
  -- 排期
  scheduled_at TIMESTAMP,
  published_at TIMESTAMP,
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 发布记录表
CREATE TABLE IF NOT EXISTS promotion_publish_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_id UUID REFERENCES promotion_contents(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- 发布信息
  platform VARCHAR(50) NOT NULL,
  platform_post_id VARCHAR(100),
  platform_url TEXT,
  
  -- 状态
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed', 'cancelled')),
  error_message TEXT,
  
  -- 时间
  scheduled_at TIMESTAMP,
  executed_at TIMESTAMP,
  
  created_at TIMESTAMP DEFAULT NOW()
);

-- 文案模板表
CREATE TABLE IF NOT EXISTS promotion_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- 模板信息
  name VARCHAR(200) NOT NULL,
  description TEXT,
  category VARCHAR(50),
  
  -- 模板内容
  content TEXT NOT NULL,
  variables JSONB DEFAULT '[]',
  
  -- 适用平台
  platforms TEXT[],
  
  -- 系统模板/用户自定义
  is_system BOOLEAN DEFAULT false,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- 使用统计
  usage_count INTEGER DEFAULT 0,
  
  created_at TIMESTAMP DEFAULT NOW()
);

-- 素材库表
CREATE TABLE IF NOT EXISTS promotion_assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- 素材信息
  name VARCHAR(200),
  type VARCHAR(20) CHECK (type IN ('image', 'video', 'text', 'link')),
  url TEXT,
  content TEXT,
  
  -- 元数据
  tags TEXT[],
  usage_count INTEGER DEFAULT 0,
  
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE promotion_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotion_publish_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotion_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotion_assets ENABLE ROW LEVEL SECURITY;

-- RLS策略：用户只能看到自己的数据
CREATE POLICY "用户查看自己的推广内容" ON promotion_contents
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建推广内容" ON promotion_contents
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户更新自己的推广内容" ON promotion_contents
FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户删除自己的推广内容" ON promotion_contents
FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "用户查看自己的发布记录" ON promotion_publish_logs
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建发布记录" ON promotion_publish_logs
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户查看系统模板" ON promotion_templates
FOR SELECT USING (is_system = true OR auth.uid() = user_id);

CREATE POLICY "用户创建自定义模板" ON promotion_templates
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户查看自己的素材" ON promotion_assets
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建素材" ON promotion_assets
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 插入系统默认模板
INSERT INTO promotion_templates (name, description, category, content, platforms, is_system) VALUES
('新功能上线-故事型', '从痛点到解决方案的故事型文案', '新功能上线', 
'{{toolName}}终于来了！

作为{{userType}}，你是否也遇到过{{painPoint}}的困扰？

{{toolName}}就是为解决这个痛点而生的：
{{features}}

现在就来体验吧！{{link}}', 
ARRAY['wechat', 'xiaohongshu', 'jike'], true),

('项目推荐-亮点型', '突出核心功能亮点的推荐文案', '项目推荐', 
'推荐一个超实用的工具：{{toolName}}

核心亮点：
{{features}}

适合人群：{{targetUsers}}

体验地址：{{link}}', 
ARRAY['wechat', 'zhihu', 'jike', 'weibo'], true),

('活动招募-紧迫感型', '制造紧迫感的活动招募文案', '活动招募', 
'限时招募！{{activityName}}

{{activityDesc}}

名额有限，仅剩{{remaining}}个名额！

截止时间：{{deadline}}

立即报名：{{link}}', 
ARRAY['wechat', 'xiaohongshu', 'pengyouquan'], true);