-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

INSERT INTO profiles (id, username, role, bio, avatar_url, created_at)
VALUES (
  '1a5e79f6-6655-4853-b11c-1446d8f6902b',
  '管理员',
  'admin',
  '虾蛋星球管理员账号',
  NULL,
  NOW()
);