-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- ============================================
-- 平台健康监控与熔断器系统
-- 解决多平台API依赖服务中断风险
-- ============================================

-- 1. 平台健康状态表（熔断器核心表）
CREATE TABLE IF NOT EXISTS platform_health_status (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform VARCHAR(50) NOT NULL UNIQUE,
  platform_name TEXT NOT NULL,
  category VARCHAR(30) NOT NULL, -- tech, social, media, international
  
  -- 健康状态
  status VARCHAR(20) DEFAULT 'healthy' CHECK (status IN ('healthy', 'degraded', 'unhealthy', 'circuit_open')),
  last_check_at TIMESTAMP DEFAULT NOW(),
  last_success_at TIMESTAMP,
  last_failure_at TIMESTAMP,
  
  -- 熔断器配置
  failure_threshold INTEGER DEFAULT 5, -- 连续失败多少次后熔断
  recovery_timeout INTEGER DEFAULT 300, -- 熔断后多久尝试恢复（秒）
  success_threshold INTEGER DEFAULT 2, -- 连续成功多少次后恢复
  
  -- 统计信息
  consecutive_failures INTEGER DEFAULT 0,
  consecutive_successes INTEGER DEFAULT 0,
  total_requests INTEGER DEFAULT 0,
  total_failures INTEGER DEFAULT 0,
  avg_response_time INTEGER DEFAULT 0, -- 毫秒
  
  -- 降级策略
  fallback_strategy VARCHAR(30) DEFAULT 'skip' CHECK (fallback_strategy IN ('skip', 'queue', 'manual', 'alternative')),
  alternative_platform VARCHAR(50), -- 替代平台
  
  -- 元数据
  api_endpoint TEXT,
  health_check_endpoint TEXT,
  is_active BOOLEAN DEFAULT true,
  priority INTEGER DEFAULT 100, -- 优先级，数字越小优先级越高
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. 平台健康检查日志表
CREATE TABLE IF NOT EXISTS platform_health_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform VARCHAR(50) NOT NULL,
  check_type VARCHAR(20) NOT NULL CHECK (check_type IN ('scheduled', 'manual', 'before_publish')),
  
  -- 检查结果
  is_healthy BOOLEAN NOT NULL,
  response_time INTEGER, -- 毫秒
  http_status INTEGER,
  error_message TEXT,
  
  -- 熔断器状态变更
  previous_status VARCHAR(20),
  current_status VARCHAR(20),
  status_changed BOOLEAN DEFAULT false,
  
  checked_at TIMESTAMP DEFAULT NOW()
);

-- 3. 发布任务队列表（用于失败重试和降级）
CREATE TABLE IF NOT EXISTS publish_task_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content_id UUID NOT NULL,
  platform VARCHAR(50) NOT NULL,
  
  -- 任务状态
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'retrying', 'completed', 'failed', 'cancelled')),
  priority INTEGER DEFAULT 100, -- 数字越小优先级越高
  
  -- 重试配置
  retry_count INTEGER DEFAULT 0,
  max_retries INTEGER DEFAULT 3,
  next_retry_at TIMESTAMP,
  
  -- 执行记录
  last_error TEXT,
  last_error_type VARCHAR(30),
  executed_at TIMESTAMP,
  completed_at TIMESTAMP,
  
  -- 结果
  platform_post_id TEXT,
  platform_url TEXT,
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 4. 平台分组表（用于冗余和自动切换）
CREATE TABLE IF NOT EXISTS platform_groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  category VARCHAR(30) NOT NULL, -- tech_social, short_video, blog, international
  platforms TEXT[] NOT NULL, -- 平台代码数组
  primary_platform VARCHAR(50) NOT NULL,
  failover_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 5. 平台依赖关系表
CREATE TABLE IF NOT EXISTS platform_dependencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform VARCHAR(50) NOT NULL,
  depends_on VARCHAR(50) NOT NULL, -- 依赖的平台（如某些平台需要Twitter授权）
  dependency_type VARCHAR(30) DEFAULT 'auth' CHECK (dependency_type IN ('auth', 'api', 'service')),
  is_required BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(platform, depends_on)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_platform_health_status ON platform_health_status(platform, status);
CREATE INDEX IF NOT EXISTS idx_platform_health_logs_platform ON platform_health_logs(platform, checked_at);
CREATE INDEX IF NOT EXISTS idx_publish_task_queue_user ON publish_task_queue(user_id, status);
CREATE INDEX IF NOT EXISTS idx_publish_task_queue_next_retry ON publish_task_queue(status, next_retry_at);

-- 启用RLS
ALTER TABLE platform_health_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_health_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE publish_task_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_dependencies ENABLE ROW LEVEL SECURITY;

-- RLS策略：平台健康状态（所有人可查看，仅管理员可修改）
CREATE POLICY "所有人可查看平台健康状态" ON platform_health_status
  FOR SELECT USING (true);

CREATE POLICY "仅管理员可修改平台健康状态" ON platform_health_status
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- RLS策略：健康日志（所有人可查看）
CREATE POLICY "所有人可查看健康日志" ON platform_health_logs
  FOR SELECT USING (true);

-- RLS策略：发布任务队列（用户只能看到自己的任务）
CREATE POLICY "用户可查看自己的发布任务" ON publish_task_queue
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "用户可创建发布任务" ON publish_task_queue
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "用户可更新自己的发布任务" ON publish_task_queue
  FOR UPDATE USING (user_id = auth.uid());

-- RLS策略：平台分组（所有人可查看）
CREATE POLICY "所有人可查看平台分组" ON platform_groups
  FOR SELECT USING (true);

-- RLS策略：平台依赖（所有人可查看）
CREATE POLICY "所有人可查看平台依赖" ON platform_dependencies
  FOR SELECT USING (true);

-- 插入初始平台数据（30+平台）
INSERT INTO platform_health_status (platform, platform_name, category, fallback_strategy, alternative_platform, priority, api_endpoint, health_check_endpoint) VALUES
-- 技术社区
('github', 'GitHub', 'tech', 'manual', NULL, 10, 'https://api.github.com', 'https://api.github.com'),
('juejin', '掘金', 'tech', 'alternative', 'csdn', 20, 'https://api.juejin.cn', 'https://api.juejin.cn/content_api/v1'),
('csdn', 'CSDN', 'tech', 'alternative', 'juejin', 30, 'https://api.csdn.net', 'https://api.csdn.net'),
('v2ex', 'V2EX', 'tech', 'alternative', 'segmentfault', 40, 'https://www.v2ex.com/api', 'https://www.v2ex.com/api/v2'),
('segmentfault', 'SegmentFault', 'tech', 'alternative', 'v2ex', 50, 'https://segmentfault.com/api', 'https://segmentfault.com'),
('jianshu', '简书', 'tech', 'skip', NULL, 60, 'https://api.jianshu.io', 'https://api.jianshu.io'),

-- 社交媒体
('weibo', '微博', 'social', 'alternative', 'twitter', 15, 'https://api.weibo.com', 'https://api.weibo.com/2'),
('zhihu', '知乎', 'social', 'alternative', 'jike', 25, 'https://www.zhihu.com/api', 'https://www.zhihu.com/api/v4'),
('jike', '即刻', 'social', 'alternative', 'zhihu', 35, 'https://api.ruguoapp.com', 'https://api.ruguoapp.com'),
('xiaohongshu', '小红书', 'social', 'skip', NULL, 45, 'https://edith.xiaohongshu.com', 'https://edith.xiaohongshu.com'),
('wechat', '微信公众号', 'social', 'manual', NULL, 5, 'https://api.weixin.qq.com', 'https://api.weixin.qq.com'),
('pengyouquan', '朋友圈', 'social', 'manual', NULL, 55, '', ''),

-- 短视频平台
('douyin', '抖音', 'media', 'alternative', 'kuaishou', 70, 'https://open.douyin.com', 'https://open.douyin.com'),
('kuaishou', '快手', 'media', 'alternative', 'douyin', 80, 'https://open.kuaishou.com', 'https://open.kuaishou.com'),
('bilibili', 'B站', 'media', 'skip', NULL, 65, 'https://api.bilibili.com', 'https://api.bilibili.com'),

-- 资讯平台
('toutiao', '今日头条', 'media', 'alternative', 'baijiahao', 75, 'https://open.snssdk.com', 'https://open.snssdk.com'),
('baijiahao', '百家号', 'media', 'alternative', 'toutiao', 85, 'https://baijiahao.baidu.com', 'https://baijiahao.baidu.com'),
('sohu', '搜狐号', 'media', 'skip', NULL, 90, 'https://mp.sohu.com', 'https://mp.sohu.com'),
('netease', '网易号', 'media', 'skip', NULL, 95, 'https://mp.163.com', 'https://mp.163.com'),

-- 国际平台
('twitter', 'Twitter/X', 'international', 'alternative', 'weibo', 12, 'https://api.twitter.com', 'https://api.twitter.com/2'),
('linkedin', 'LinkedIn', 'international', 'skip', NULL, 22, 'https://api.linkedin.com', 'https://api.linkedin.com/v2'),
('producthunt', 'Product Hunt', 'international', 'manual', NULL, 8, 'https://api.producthunt.com', 'https://api.producthunt.com/v2'),
('hackernews', 'Hacker News', 'international', 'manual', NULL, 28, 'https://hacker-news.firebaseio.com', 'https://hacker-news.firebaseio.com'),
('reddit', 'Reddit', 'international', 'skip', NULL, 38, 'https://oauth.reddit.com', 'https://oauth.reddit.com'),
('devto', 'Dev.to', 'international', 'alternative', 'medium', 48, 'https://dev.to/api', 'https://dev.to/api'),
('medium', 'Medium', 'international', 'alternative', 'devto', 58, 'https://api.medium.com', 'https://api.medium.com/v1'),
('discord', 'Discord', 'international', 'skip', NULL, 68, 'https://discord.com/api', 'https://discord.com/api/v10'),
('telegram', 'Telegram', 'international', 'skip', NULL, 78, 'https://api.telegram.org', 'https://api.telegram.org');

-- 插入平台分组数据
INSERT INTO platform_groups (name, description, category, platforms, primary_platform, failover_enabled) VALUES
('tech_community', '技术社区平台组', 'tech_social', ARRAY['juejin', 'csdn', 'v2ex', 'segmentfault', 'jianshu'], 'juejin', true),
('social_media', '社交媒体平台组', 'social', ARRAY['weibo', 'zhihu', 'jike', 'xiaohongshu'], 'zhihu', true),
('short_video', '短视频平台组', 'media', ARRAY['douyin', 'kuaishou', 'bilibili'], 'bilibili', true),
('news_platform', '资讯平台组', 'media', ARRAY['toutiao', 'baijiahao', 'sohu', 'netease'], 'toutiao', true),
('international', '国际平台组', 'international', ARRAY['twitter', 'linkedin', 'producthunt', 'hackernews', 'reddit', 'devto', 'medium'], 'producthunt', true);

-- 插入平台依赖关系
INSERT INTO platform_dependencies (platform, depends_on, dependency_type, is_required) VALUES
('wechat', 'wechat_auth', 'auth', true),
('xiaohongshu', 'xiaohongshu_auth', 'auth', true),
('douyin', 'douyin_auth', 'auth', true),
('kuaishou', 'kuaishou_auth', 'auth', true);