-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE tool_platform_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  platform VARCHAR(50) NOT NULL,
  platform_name VARCHAR(100) NOT NULL,
  url TEXT NOT NULL,
  icon VARCHAR(50),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE tool_platform_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看平台链接" ON tool_platform_links FOR SELECT USING (true);
CREATE POLICY "开发者可管理自己的平台链接" ON tool_platform_links FOR ALL USING (
  EXISTS (
    SELECT 1 FROM tools WHERE tools.id = tool_platform_links.tool_id AND tools.developer_id = auth.uid()
  )
);