-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 分类表
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  icon TEXT,
  sort_order INTEGER DEFAULT 0,
  tool_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户资料表
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  avatar_url TEXT,
  bio TEXT,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 工具表
CREATE TABLE tools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  developer_story TEXT,
  category_id UUID REFERENCES categories(id),
  tags TEXT[],
  icon_url TEXT,
  screenshots TEXT[],
  jump_url TEXT NOT NULL,
  jump_type TEXT NOT NULL CHECK (jump_type IN ('miniprogram', 'h5', 'app')),
  developer_id UUID REFERENCES profiles(id),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  is_premium BOOLEAN DEFAULT false,
  view_count INTEGER DEFAULT 0,
  jump_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 轻量级IP确权表
CREATE TABLE tool_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID REFERENCES tools(id) ON DELETE CASCADE,
  certificate_code TEXT UNIQUE NOT NULL,
  hash_value TEXT NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  certificate_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 收藏表
CREATE TABLE favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  tool_id UUID REFERENCES tools(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, tool_id)
);

-- 评论表
CREATE TABLE comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID REFERENCES tools(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  parent_id UUID REFERENCES comments(id) ON DELETE CASCADE,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- RLS策略
CREATE POLICY "公开读取用户资料" ON profiles FOR SELECT USING (true);
CREATE POLICY "用户更新自己的资料" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "公开读取已审核工具" ON tools FOR SELECT USING (status = 'approved');
CREATE POLICY "开发者管理自己的工具" ON tools FOR ALL USING (auth.uid() = developer_id);

CREATE POLICY "公开读取确权信息" ON tool_certificates FOR SELECT USING (true);

CREATE POLICY "用户管理自己的收藏" ON favorites FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "公开读取评论" ON comments FOR SELECT USING (true);
CREATE POLICY "用户管理自己的评论" ON comments FOR ALL USING (auth.uid() = user_id);

-- 插入示例分类数据
INSERT INTO categories (name, icon, sort_order) VALUES 
('效率工具', 'zap', 1),
('生活助手', 'home', 2),
('健康运动', 'heart', 3),
('学习教育', 'book', 4),
('娱乐休闲', 'gamepad', 5),
('金融理财', 'dollar-sign', 6),
('开发工具', 'code', 7),
('其他', 'more-horizontal', 8);