-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID NOT NULL REFERENCES public.demands(id) ON DELETE CASCADE,
  quote_id UUID NOT NULL REFERENCES public.quotes(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "需求发布者可查看自己的对接" ON public.connections
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "开发者可查看自己的对接" ON public.connections
FOR SELECT USING (developer_id = auth.uid());

CREATE POLICY "需求发布者可创建对接" ON public.connections
FOR INSERT WITH CHECK (
  auth.uid() IS NOT NULL 
  AND user_id = auth.uid()
);

CREATE POLICY "需求发布者可更新自己的对接" ON public.connections
FOR UPDATE USING (user_id = auth.uid());

COMMENT ON TABLE public.connections IS '需求撮合-对接表';
COMMENT ON COLUMN public.connections.status IS '状态：active对接中/completed已完成/cancelled已取消';