-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建开发者申请表
CREATE TABLE IF NOT EXISTS developer_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  company_name TEXT,
  contact_name TEXT NOT NULL,
  contact_phone TEXT,
  portfolio_url TEXT,
  bio TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  applied_at TIMESTAMP DEFAULT NOW(),
  reviewed_at TIMESTAMP,
  reviewed_by UUID REFERENCES auth.users(id),
  rejection_reason TEXT
);

-- 创建星推官表
CREATE TABLE IF NOT EXISTS promoters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  commission_rate DECIMAL(5,2) DEFAULT 10.00,
  total_earned DECIMAL(10,2) DEFAULT 0.00,
  total_withdrawn DECIMAL(10,2) DEFAULT 0.00,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
  joined_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 创建佣金提现表
CREATE TABLE IF NOT EXISTS commission_withdrawals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  promoter_id UUID NOT NULL REFERENCES promoters(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  payment_method TEXT,
  payment_account TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'rejected')),
  created_at TIMESTAMP DEFAULT NOW(),
  processed_at TIMESTAMP,
  rejection_reason TEXT
);

-- 启用RLS
ALTER TABLE developer_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE promoters ENABLE ROW LEVEL SECURITY;
ALTER TABLE commission_withdrawals ENABLE ROW LEVEL SECURITY;

-- 开发者申请表RLS策略
CREATE POLICY "用户可查看自己的申请" ON developer_applications
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "用户可创建申请" ON developer_applications
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "管理员可查看所有申请" ON developer_applications
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 星推官表RLS策略
CREATE POLICY "用户可查看自己的星推官信息" ON promoters
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "管理员可管理星推官" ON promoters
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 佣金提现表RLS策略
CREATE POLICY "星推官可查看自己的提现记录" ON commission_withdrawals
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM promoters WHERE id = commission_withdrawals.promoter_id AND user_id = auth.uid())
  );

CREATE POLICY "星推官可申请提现" ON commission_withdrawals
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM promoters WHERE id = commission_withdrawals.promoter_id AND user_id = auth.uid())
  );

CREATE POLICY "管理员可管理提现" ON commission_withdrawals
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );