-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS tool_promotion_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  promotion_type VARCHAR(20) NOT NULL CHECK (promotion_type IN ('self', 'promoter')),
  promoter_fee_percentage DECIMAL(5,2) DEFAULT 0,
  platform_fee_percentage DECIMAL(5,2) DEFAULT 10.00,
  min_promoter_reward DECIMAL(10,2) DEFAULT 0,
  max_promoter_reward DECIMAL(10,2) DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(tool_id)
);

ALTER TABLE tool_promotion_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "开发者可查看自己的推广设置" ON tool_promotion_settings
  FOR SELECT USING (developer_id = auth.uid());

CREATE POLICY "开发者可创建自己的推广设置" ON tool_promotion_settings
  FOR INSERT WITH CHECK (developer_id = auth.uid());

CREATE POLICY "开发者可更新自己的推广设置" ON tool_promotion_settings
  FOR UPDATE USING (developer_id = auth.uid());

CREATE POLICY "开发者可删除自己的推广设置" ON tool_promotion_settings
  FOR DELETE USING (developer_id = auth.uid());

CREATE POLICY "所有人可查看推广设置" ON tool_promotion_settings
  FOR SELECT USING (true);