-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修复开发者入驻页面的 RLS 策略问题

-- 1. 确保 tool_platform_links 表有正确的 INSERT 策略
-- 先检查是否存在，如果存在则删除重建
DROP POLICY IF EXISTS "开发者可管理自己的平台链接" ON tool_platform_links;

-- 创建新的策略，允许开发者插入平台链接
CREATE POLICY "开发者可管理自己的平台链接" ON tool_platform_links
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM tools WHERE tools.id = tool_platform_links.tool_id AND tools.developer_id = auth.uid()
  )
);

-- 2. 确保 tools 表允许开发者插入自己的工具
DROP POLICY IF EXISTS "开发者可插入自己的工具" ON tools;

CREATE POLICY "开发者可插入自己的工具" ON tools
FOR INSERT WITH CHECK (auth.uid() = developer_id);

-- 3. 确保 developer_applications 表有正确的 RLS 策略
-- 允许用户查看自己的申请
DROP POLICY IF EXISTS "用户可查看自己的开发者申请" ON developer_applications;

CREATE POLICY "用户可查看自己的开发者申请" ON developer_applications
FOR SELECT USING (auth.uid() = user_id);

-- 允许用户插入自己的申请
DROP POLICY IF EXISTS "用户可创建开发者申请" ON developer_applications;

CREATE POLICY "用户可创建开发者申请" ON developer_applications
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 允许用户更新自己的申请
DROP POLICY IF EXISTS "用户可更新自己的开发者申请" ON developer_applications;

CREATE POLICY "用户可更新自己的开发者申请" ON developer_applications
FOR UPDATE USING (auth.uid() = user_id);