-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建聊天会话表
CREATE TABLE IF NOT EXISTS chat_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID REFERENCES demands(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  quote_id UUID REFERENCES quotes(id) ON DELETE SET NULL,
  status VARCHAR(20) DEFAULT 'active',
  last_message_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建聊天消息表
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  message_type VARCHAR(20) DEFAULT 'text',
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建开发者信誉表
CREATE TABLE IF NOT EXISTS developer_reputation (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  developer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  level INTEGER DEFAULT 1,
  score INTEGER DEFAULT 100,
  total_orders INTEGER DEFAULT 0,
  completed_orders INTEGER DEFAULT 0,
  rating DECIMAL(2,1) DEFAULT 5.0,
  response_rate INTEGER DEFAULT 100,
  on_time_rate INTEGER DEFAULT 100,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(developer_id)
);

-- 创建评价表
CREATE TABLE IF NOT EXISTS reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID REFERENCES demands(id) ON DELETE SET NULL,
  reviewer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content TEXT,
  tags TEXT[],
  is_public BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建需求置顶订单表
CREATE TABLE IF NOT EXISTS demand_boosts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID NOT NULL REFERENCES demands(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  boost_type VARCHAR(20) NOT NULL,
  duration_days INTEGER NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  start_at TIMESTAMP,
  end_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  paid_at TIMESTAMP
);

-- 创建星推官撮合推广表
CREATE TABLE IF NOT EXISTS promoter_demand_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  demand_id UUID NOT NULL REFERENCES demands(id) ON DELETE CASCADE,
  promoter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  code VARCHAR(50) NOT NULL UNIQUE,
  click_count INTEGER DEFAULT 0,
  quote_count INTEGER DEFAULT 0,
  connected_count INTEGER DEFAULT 0,
  commission_earned DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE developer_reputation ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE demand_boosts ENABLE ROW LEVEL SECURITY;
ALTER TABLE promoter_demand_links ENABLE ROW LEVEL SECURITY;

-- 聊天会话RLS策略
CREATE POLICY "用户可查看自己的聊天会话" ON chat_conversations
  FOR SELECT USING (user_id = auth.uid() OR developer_id = auth.uid());

CREATE POLICY "用户可创建聊天会话" ON chat_conversations
  FOR INSERT WITH CHECK (user_id = auth.uid() OR developer_id = auth.uid());

-- 聊天消息RLS策略
CREATE POLICY "用户可查看会话消息" ON chat_messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM chat_conversations 
      WHERE id = chat_messages.conversation_id 
      AND (user_id = auth.uid() OR developer_id = auth.uid())
    )
  );

CREATE POLICY "会话参与者可发送消息" ON chat_messages
  FOR INSERT WITH CHECK (
    sender_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM chat_conversations 
      WHERE id = chat_messages.conversation_id 
      AND (user_id = auth.uid() OR developer_id = auth.uid())
    )
  );

-- 开发者信誉RLS策略
CREATE POLICY "所有人可查看开发者信誉" ON developer_reputation
  FOR SELECT USING (true);

-- 评价RLS策略
CREATE POLICY "所有人可查看公开评价" ON reviews
  FOR SELECT USING (is_public = true);

CREATE POLICY "用户可创建评价" ON reviews
  FOR INSERT WITH CHECK (reviewer_id = auth.uid());

-- 置顶订单RLS策略
CREATE POLICY "用户可查看自己的置顶订单" ON demand_boosts
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "用户可创建置顶订单" ON demand_boosts
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- 星推官链接RLS策略
CREATE POLICY "星推官可查看自己的推广链接" ON promoter_demand_links
  FOR SELECT USING (promoter_id = auth.uid());

CREATE POLICY "星推官可创建推广链接" ON promoter_demand_links
  FOR INSERT WITH CHECK (promoter_id = auth.uid());

-- 创建实时发布
ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;