-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为 promotion-assets bucket 添加 RLS 策略
-- 允许所有用户上传文件
CREATE POLICY "允许所有用户上传推广资源" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'promotion-assets');

-- 允许所有用户查看文件
CREATE POLICY "允许所有用户查看推广资源" ON storage.objects
FOR SELECT USING (bucket_id = 'promotion-assets');

-- 允许所有用户更新自己的文件
CREATE POLICY "允许所有用户更新推广资源" ON storage.objects
FOR UPDATE USING (bucket_id = 'promotion-assets');

-- 允许所有用户删除自己的文件
CREATE POLICY "允许所有用户删除推广资源" ON storage.objects
FOR DELETE USING (bucket_id = 'promotion-assets');