-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.promotion_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id UUID NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  developer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reward_amount DECIMAL(10, 2) NOT NULL DEFAULT 5.00,
  target_clicks INTEGER NOT NULL DEFAULT 100,
  current_clicks INTEGER NOT NULL DEFAULT 0,
  total_budget DECIMAL(10, 2) NOT NULL,
  spent_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'expired')),
  start_date TIMESTAMP NOT NULL DEFAULT NOW(),
  end_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.promotion_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看进行中的悬赏" ON public.promotion_tasks
  FOR SELECT USING (status = 'active' AND end_date > NOW());

CREATE POLICY "开发者可管理自己的悬赏" ON public.promotion_tasks
  FOR ALL USING (developer_id = auth.uid());

CREATE INDEX idx_promotion_tasks_status ON public.promotion_tasks(status);
CREATE INDEX idx_promotion_tasks_tool_id ON public.promotion_tasks(tool_id);
CREATE INDEX idx_promotion_tasks_developer_id ON public.promotion_tasks(developer_id);